// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT License.
// See the LICENSE file in the project root for more information.

namespace Reaqtor.Remoting.Samples.Models
{
    using System.Collections.Generic;
    using Nuqleon.DataModel;

    /// <summary>
    /// The news object that carries notification information for a search-query term.
    /// </summary>
    public class NewsInfo
    {
        /// <summary>
        /// The Id that was generated by the News service and attached to the subscription when it was created.
        /// </summary>
        [Mapping("bing://reactiveprocessingentity/real/news/subscriptionid")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// The search-term the results are for.
        /// </summary>
        [Mapping("bing://reactiveprocessingentity/real/news/searchterm")]
        public string SearchQueryTerm { get; set; }

        /// <summary>
        /// A list of news results relevant to the subscription.
        /// </summary>
        [Mapping("bing://reactiveprocessingentity/real/news/results")]
        public List<NewsResult> Results { get; set; }
    }
}
